"""Remove bank_account_name column from Collection

Revision ID: 05405ce7ab56
Revises: 8e2b0111ec0c
Create Date: 2026-05-24 04:25:29.563541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05405ce7ab56'
down_revision = '8e2b0111ec0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collection', schema=None) as batch_op:
        batch_op.drop_column('bank_account_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collection', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bank_account_name', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
