"""empty message

Revision ID: 0d3bd974df9b
Revises: 1b36476e6380
Create Date: 2025-08-12 10:34:48.020673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d3bd974df9b'
down_revision = '1b36476e6380'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts_payable', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invoice_number', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts_payable', schema=None) as batch_op:
        batch_op.drop_column('invoice_number')

    # ### end Alembic commands ###
