"""Add request_action field to ChangeRequest for cancellation requests

Revision ID: 0d3b4a0a3657
Revises: 77303377fffc
Create Date: 2026-05-20 12:54:46.860687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d3b4a0a3657'
down_revision = '77303377fffc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('change_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('request_action', sa.String(length=20), nullable=True))

    # Set default value for existing rows
    op.execute("UPDATE change_request SET request_action = 'modification' WHERE request_action IS NULL")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('change_request', schema=None) as batch_op:
        batch_op.drop_column('request_action')
    # ### end Alembic commands ###
