"""Add FundCategory, FundReceived, and FundDisbursed models

Revision ID: 18122d455907
Revises: 0d3b4a0a3657
Create Date: 2026-05-20 22:05:30.336007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18122d455907'
down_revision = '0d3b4a0a3657'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fund_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fund_disbursed',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_date', sa.String(), nullable=False),
    sa.Column('fund_category_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('reference_number', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_by_id', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_by_id', sa.Integer(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('cancellation_reason', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['cancelled_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['fund_category_id'], ['fund_category.id'], ),
    sa.ForeignKeyConstraint(['submitted_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fund_received',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_date', sa.String(), nullable=False),
    sa.Column('fund_category_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('reference_number', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_by_id', sa.Integer(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by_id', sa.Integer(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_by_id', sa.Integer(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('cancellation_reason', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approved_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['cancelled_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['fund_category_id'], ['fund_category.id'], ),
    sa.ForeignKeyConstraint(['submitted_by_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('_alembic_tmp_change_request')
    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.drop_column('tin')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('superuser')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('superuser', sa.BOOLEAN(), server_default=sa.text('0'), nullable=False))

    with op.batch_alter_table('company', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tin', sa.VARCHAR(length=50), nullable=True))

    op.create_table('_alembic_tmp_change_request',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('transaction_id', sa.INTEGER(), nullable=True),
    sa.Column('old_values', sa.TEXT(), nullable=True),
    sa.Column('new_values', sa.TEXT(), nullable=True),
    sa.Column('reason', sa.VARCHAR(length=500), nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'pending'"), nullable=True),
    sa.Column('requested_by_id', sa.INTEGER(), nullable=False),
    sa.Column('requested_at', sa.DATETIME(), nullable=True),
    sa.Column('reviewed_by_id', sa.INTEGER(), nullable=True),
    sa.Column('reviewed_at', sa.DATETIME(), nullable=True),
    sa.Column('review_notes', sa.VARCHAR(length=500), nullable=True),
    sa.Column('record_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('record_id', sa.INTEGER(), nullable=False),
    sa.Column('request_action', sa.VARCHAR(length=20), nullable=True),
    sa.ForeignKeyConstraint(['requested_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('fund_received')
    op.drop_table('fund_disbursed')
    op.drop_table('fund_category')
    # ### end Alembic commands ###
