"""empty message

Revision ID: 1b36476e6380
Revises: 997d9d4ba076
Create Date: 2025-08-12 10:26:08.940865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b36476e6380'
down_revision = '997d9d4ba076'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts_payable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_date', sa.String(), nullable=True),
    sa.Column('record_number', sa.String(), nullable=True),
    sa.Column('rr_number', sa.String(), nullable=True),
    sa.Column('po_number', sa.String(), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('prepared_by', sa.String(), nullable=True),
    sa.Column('checked_by', sa.String(), nullable=True),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('submitted', sa.String(), nullable=True),
    sa.Column('cancelled', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('accounts_payable_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('accounts_payable_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('debit', sa.Float(), nullable=True),
    sa.Column('credit', sa.Float(), nullable=True),
    sa.Column('side_note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['accounts_payable_id'], ['accounts_payable.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin_accounts_payable',
    sa.Column('accounts_payable_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['accounts_payable_id'], ['accounts_payable.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('accounts_payable_id', 'user_id')
    )
    op.create_table('user_accounts_payable',
    sa.Column('accounts_payable_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['accounts_payable_id'], ['accounts_payable.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('accounts_payable_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_accounts_payable')
    op.drop_table('admin_accounts_payable')
    op.drop_table('accounts_payable_detail')
    op.drop_table('accounts_payable')
    # ### end Alembic commands ###
