"""Add is_receivable to tender

Revision ID: 2f871b1e1327
Revises: 5a1128bc792f
Create Date: 2026-05-16 16:35:10.059411

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f871b1e1327'
down_revision = '5a1128bc792f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tender', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_receivable', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tender', schema=None) as batch_op:
        batch_op.drop_column('is_receivable')

    # ### end Alembic commands ###
