"""Change deposit bank_account to bank_account_id FK

Revision ID: 3a06394544e3
Revises: 05405ce7ab56
Create Date: 2026-05-24 04:40:02.690407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a06394544e3'
down_revision = '05405ce7ab56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collection', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_collection_ape_batch_id', 'ape_batch', ['ape_batch_id'], ['id'])

    with op.batch_alter_table('deposit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bank_account_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_deposit_bank_account_id', 'bank_account', ['bank_account_id'], ['id'])
        batch_op.drop_column('bank_account')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deposit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bank_account', sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint('fk_deposit_bank_account_id', type_='foreignkey')
        batch_op.drop_column('bank_account_id')

    with op.batch_alter_table('collection', schema=None) as batch_op:
        batch_op.drop_constraint('fk_collection_ape_batch_id', type_='foreignkey')

    # ### end Alembic commands ###
