"""transaction_type as FK to transaction_type table

Revision ID: 4101a1353a9c
Revises: f0a8a9592d66
Create Date: 2026-05-16 15:13:58.965083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4101a1353a9c'
down_revision = 'f0a8a9592d66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_type_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_transaction_transaction_type', 'transaction_type', ['transaction_type_id'], ['id'])
        batch_op.drop_column('transaction_type')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_type', sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint('fk_transaction_transaction_type', type_='foreignkey')
        batch_op.drop_column('transaction_type_id')

    # ### end Alembic commands ###
