"""Add cancellation_reason to Deposit model

Revision ID: 48db4815eaa5
Revises: d970b5023c74
Create Date: 2026-05-20 07:41:01.465022

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48db4815eaa5'
down_revision = 'd970b5023c74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Only add cancellation_reason field to deposit table
    with op.batch_alter_table('deposit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cancellation_reason', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove cancellation_reason field from deposit table
    with op.batch_alter_table('deposit', schema=None) as batch_op:
        batch_op.drop_column('cancellation_reason')

    # ### end Alembic commands ###
