"""Add symbol and transaction_types to Tender

Revision ID: 48ff8bf972bc
Revises: fb97c1e9b506
Create Date: 2026-05-15 16:06:46.719359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48ff8bf972bc'
down_revision = 'fb97c1e9b506'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tender', schema=None) as batch_op:
        batch_op.add_column(sa.Column('symbol', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('transaction_types', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tender', schema=None) as batch_op:
        batch_op.drop_column('transaction_types')
        batch_op.drop_column('symbol')

    # ### end Alembic commands ###
