"""Add deductions and deduction_details to deposit table

Revision ID: 571730995d45
Revises: 53e8ba861e3a
Create Date: 2026-05-23 17:37:56.651734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '571730995d45'
down_revision = '53e8ba861e3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deposit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deductions', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('deduction_details', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deposit', schema=None) as batch_op:
        batch_op.drop_column('deduction_details')
        batch_op.drop_column('deductions')

    # ### end Alembic commands ###
