"""Add discount_description to Transaction model

Revision ID: 5a0ced8d5665
Revises: 3a06394544e3
Create Date: 2026-05-24 07:14:04.126258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a0ced8d5665'
down_revision = '3a06394544e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount_description', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('discount_description')

    # ### end Alembic commands ###
