"""Add sort_order and report_static to tender

Revision ID: 5a1128bc792f
Revises: 4101a1353a9c
Create Date: 2026-05-16 16:25:07.582062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a1128bc792f'
down_revision = '4101a1353a9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tender', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sort_order', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('report_static', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tender', schema=None) as batch_op:
        batch_op.drop_column('report_static')
        batch_op.drop_column('sort_order')

    # ### end Alembic commands ###
