"""Add transaction_type to Transaction

Revision ID: 5e23b41e4239
Revises: 48ff8bf972bc
Create Date: 2026-05-16 08:50:51.386619

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e23b41e4239'
down_revision = '48ff8bf972bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transaction_type', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('transaction_type')

    # ### end Alembic commands ###
