"""empty message

Revision ID: 6509880095ab
Revises: 39a78a15ee81
Create Date: 2025-09-08 10:11:24.995415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6509880095ab'
down_revision = '39a78a15ee81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('business_style', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('salesman', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_column('salesman')
        batch_op.drop_column('business_style')

    # ### end Alembic commands ###
