"""Add status workflow fields to Collection model

Revision ID: 77303377fffc
Revises: d91b7dbeff1c
Create Date: 2026-05-20 11:43:23.798685

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77303377fffc'
down_revision = 'd91b7dbeff1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collection', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('created_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('submitted_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('submitted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('approved_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('approved_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('cancelled_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cancelled_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('cancellation_reason', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # Set default status for existing collections
    op.execute("UPDATE collection SET status = 'posted' WHERE status IS NULL")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collection', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('cancellation_reason')
        batch_op.drop_column('cancelled_at')
        batch_op.drop_column('cancelled_by_id')
        batch_op.drop_column('approved_at')
        batch_op.drop_column('approved_by_id')
        batch_op.drop_column('submitted_at')
        batch_op.drop_column('submitted_by_id')
        batch_op.drop_column('created_by_id')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
