"""empty message

Revision ID: 84022c06743b
Revises: 6509880095ab
Create Date: 2025-09-08 12:13:06.761594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84022c06743b'
down_revision = '6509880095ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('measure',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('measure_name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin_measure',
    sa.Column('measure_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['measure_id'], ['measure.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('measure_id', 'user_id')
    )
    op.create_table('user_measure',
    sa.Column('measure_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['measure_id'], ['measure.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('measure_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_measure')
    op.drop_table('admin_measure')
    op.drop_table('measure')
    # ### end Alembic commands ###
