"""Add deductions and bank_account_name to Collection model

Revision ID: 8e2b0111ec0c
Revises: f2121b701c6c
Create Date: 2026-05-24 04:14:47.588565

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e2b0111ec0c'
down_revision = 'f2121b701c6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collection', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bank_account_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('deductions', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('collection', schema=None) as batch_op:
        batch_op.drop_column('deductions')
        batch_op.drop_column('bank_account_name')

    # ### end Alembic commands ###
