"""empty message

Revision ID: 8ebcb2bbf679
Revises: feb9b1347ce1
Create Date: 2026-05-10 22:31:50.249672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ebcb2bbf679'
down_revision = 'feb9b1347ce1'
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    existing_tables = inspector.get_table_names()

    # ### commands auto generated by Alembic - please adjust! ###
    if 'product_type' not in existing_tables:
        op.create_table('product_type',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('product_type_name', sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )

    if 'sex' not in existing_tables:
        op.create_table('sex',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('sex_name', sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )

    if 'tender' not in existing_tables:
        op.create_table('tender',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('tender_name', sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )

    if 'admin_product_type' not in existing_tables:
        op.create_table('admin_product_type',
        sa.Column('product_type_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['product_type_id'], ['product_type.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('product_type_id', 'user_id')
        )

    if 'admin_sex' not in existing_tables:
        op.create_table('admin_sex',
        sa.Column('sex_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['sex_id'], ['sex.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('sex_id', 'user_id')
        )

    if 'admin_tender' not in existing_tables:
        op.create_table('admin_tender',
        sa.Column('tender_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['tender_id'], ['tender.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('tender_id', 'user_id')
        )

    if 'user_product_type' not in existing_tables:
        op.create_table('user_product_type',
        sa.Column('product_type_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['product_type_id'], ['product_type.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('product_type_id', 'user_id')
        )

    if 'user_sex' not in existing_tables:
        op.create_table('user_sex',
        sa.Column('sex_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['sex_id'], ['sex.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('sex_id', 'user_id')
        )

    if 'user_tender' not in existing_tables:
        op.create_table('user_tender',
        sa.Column('tender_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['tender_id'], ['tender.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
        sa.PrimaryKeyConstraint('tender_id', 'user_id')
        )

    # Column additions use get_columns() to check existence per table
    existing_customer_columns = [c['name'] for c in inspector.get_columns('customer')]
    with op.batch_alter_table('customer', schema=None) as batch_op:
        if 'birthday' not in existing_customer_columns:
            batch_op.add_column(sa.Column('birthday', sa.String(), nullable=True))
        if 'sex_id' not in existing_customer_columns:
            batch_op.add_column(sa.Column('sex_id', sa.Integer(), nullable=False))
            batch_op.create_foreign_key("CustomerInfo", 'sex', ['sex_id'], ['id'])

    existing_product_columns = [c['name'] for c in inspector.get_columns('product')]
    with op.batch_alter_table('product', schema=None) as batch_op:
        if 'product_type_id' not in existing_product_columns:
            batch_op.add_column(sa.Column('product_type_id', sa.Integer(), nullable=False))
            batch_op.create_foreign_key("ProductTypeInfo", 'product_type', ['product_type_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint("ProductTypeInfo", type_='foreignkey')
        batch_op.drop_column('product_type_id')

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_constraint("CustomerInfo", type_='foreignkey')
        batch_op.drop_column('sex_id')
        batch_op.drop_column('birthday')

    op.drop_table('user_tender')
    op.drop_table('user_sex')
    op.drop_table('user_product_type')
    op.drop_table('admin_tender')
    op.drop_table('admin_sex')
    op.drop_table('admin_product_type')
    op.drop_table('tender')
    op.drop_table('sex')
    op.drop_table('product_type')
    # ### end Alembic commands ###