"""Add TransactionType model

Revision ID: 8f95916918c0
Revises: 5e23b41e4239
Create Date: 2026-05-16 09:00:33.248931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f95916918c0'
down_revision = '5e23b41e4239'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transaction_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type_code', sa.String(), nullable=False),
    sa.Column('type_name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('icon_color', sa.String(), nullable=True),
    sa.Column('badge_color', sa.String(), nullable=True),
    sa.Column('report_category', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type_code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transaction_type')
    # ### end Alembic commands ###
