"""empty message

Revision ID: 9dc7ba07931a
Revises: e77bcdf3310c
Create Date: 2025-08-29 06:08:40.378531

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dc7ba07931a'
down_revision = 'e77bcdf3310c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disbursement_extra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_date', sa.String(), nullable=True),
    sa.Column('record_number', sa.String(), nullable=True),
    sa.Column('po_number', sa.String(), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('ap_number', sa.String(), nullable=True),
    sa.Column('prepared_by', sa.String(), nullable=True),
    sa.Column('checked_by', sa.String(), nullable=True),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('submitted', sa.String(), nullable=True),
    sa.Column('cancelled', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin_disbursement_extra',
    sa.Column('disbursement_extra_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['disbursement_extra_id'], ['disbursement_extra.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('disbursement_extra_id', 'user_id')
    )
    op.create_table('disbursement_extra_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('disbursement_extra_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('debit', sa.Float(), nullable=True),
    sa.Column('credit', sa.Float(), nullable=True),
    sa.Column('side_note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['disbursement_extra_id'], ['disbursement_extra.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_disbursement_extra',
    sa.Column('disbursement_extra_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['disbursement_extra_id'], ['disbursement_extra.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('disbursement_extra_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_disbursement_extra')
    op.drop_table('disbursement_extra_detail')
    op.drop_table('admin_disbursement_extra')
    op.drop_table('disbursement_extra')
    # ### end Alembic commands ###
