"""empty message

Revision ID: af0a4ceb826b
Revises: feb9b1347ce1
Create Date: 2026-05-07 14:49:12.786567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af0a4ceb826b'
down_revision = 'feb9b1347ce1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tender',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tender_name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin_tender',
    sa.Column('tender_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tender_id'], ['tender.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('tender_id', 'user_id')
    )
    op.create_table('user_tender',
    sa.Column('tender_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tender_id'], ['tender.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('tender_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_tender')
    op.drop_table('admin_tender')
    op.drop_table('tender')
    # ### end Alembic commands ###
