"""empty message

Revision ID: bf8d5ff3214d
Revises: 8e6d73f29e69
Create Date: 2026-05-07 15:16:19.095380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf8d5ff3214d'
down_revision = '8e6d73f29e69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_type_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('ProductType', 'product_type', ['product_type_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint('ProductType', type_='foreignkey')
        batch_op.drop_column('product_type_id')

    # ### end Alembic commands ###
