"""Add status and approval fields to ReimbursementReceived

Revision ID: d57d6eb765b4
Revises: 5a0ced8d5665
Create Date: 2026-05-24 11:01:51.190499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd57d6eb765b4'
down_revision = '5a0ced8d5665'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reimbursement_received', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('submitted_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('submitted_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('approved_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('approved_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key('fk_reimbursement_received_approved_by', 'user', ['approved_by_id'], ['id'])
        batch_op.create_foreign_key('fk_reimbursement_received_submitted_by', 'user', ['submitted_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reimbursement_received', schema=None) as batch_op:
        batch_op.drop_constraint('fk_reimbursement_received_submitted_by', type_='foreignkey')
        batch_op.drop_constraint('fk_reimbursement_received_approved_by', type_='foreignkey')
        batch_op.drop_column('approved_at')
        batch_op.drop_column('approved_by_id')
        batch_op.drop_column('submitted_at')
        batch_op.drop_column('submitted_by_id')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
