"""Add record_type and record_id to ChangeRequest for deposits support

Revision ID: d91b7dbeff1c
Revises: 48db4815eaa5
Create Date: 2026-05-20 08:03:28.436219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd91b7dbeff1c'
down_revision = '48db4815eaa5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Only modify change_request table
    with op.batch_alter_table('change_request', schema=None) as batch_op:
        # Add new columns with defaults since table might have data
        batch_op.add_column(sa.Column('record_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('record_id', sa.Integer(), nullable=True))
        # Make transaction_id nullable for backwards compatibility
        batch_op.alter_column('transaction_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # Populate record_type and record_id for existing records
    op.execute("UPDATE change_request SET record_type = 'transaction', record_id = transaction_id WHERE transaction_id IS NOT NULL")

    # Now make them NOT NULL after populating
    with op.batch_alter_table('change_request', schema=None) as batch_op:
        batch_op.alter_column('record_type',
               existing_type=sa.String(length=20),
               nullable=False)
        batch_op.alter_column('record_id',
               existing_type=sa.Integer(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove the new columns
    with op.batch_alter_table('change_request', schema=None) as batch_op:
        batch_op.drop_column('record_id')
        batch_op.drop_column('record_type')
        # Restore transaction_id to NOT NULL
        batch_op.alter_column('transaction_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
