"""Add cancelled_by_id and cancelled_at to Deposit model

Revision ID: d970b5023c74
Revises: 8034460e8e5f
Create Date: 2026-05-20 07:37:31.417157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd970b5023c74'
down_revision = '8034460e8e5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Only add the cancelled fields to deposit table
    with op.batch_alter_table('deposit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cancelled_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cancelled_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key('fk_deposit_cancelled_by_user', 'user', ['cancelled_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove the cancelled fields from deposit table
    with op.batch_alter_table('deposit', schema=None) as batch_op:
        batch_op.drop_constraint('fk_deposit_cancelled_by_user', type_='foreignkey')
        batch_op.drop_column('cancelled_at')
        batch_op.drop_column('cancelled_by_id')

    # ### end Alembic commands ###
