"""empty message

Revision ID: e77bcdf3310c
Revises: 994a036f5586
Create Date: 2025-08-27 15:34:44.901222

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e77bcdf3310c'
down_revision = '994a036f5586'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts_payable_extra',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_date', sa.String(), nullable=True),
    sa.Column('record_number', sa.String(), nullable=True),
    sa.Column('invoice_number', sa.String(), nullable=True),
    sa.Column('rr_number', sa.String(), nullable=True),
    sa.Column('po_number', sa.String(), nullable=True),
    sa.Column('vendor_id', sa.Integer(), nullable=False),
    sa.Column('prepared_by', sa.String(), nullable=True),
    sa.Column('checked_by', sa.String(), nullable=True),
    sa.Column('approved_by', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('submitted', sa.String(), nullable=True),
    sa.Column('cancelled', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('accounts_payable_extra_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('accounts_payable_extra_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('debit', sa.Float(), nullable=True),
    sa.Column('credit', sa.Float(), nullable=True),
    sa.Column('side_note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['accounts_payable_extra_id'], ['accounts_payable_extra.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin_accounts_payable_extra',
    sa.Column('accounts_payable_extra_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['accounts_payable_extra_id'], ['accounts_payable_extra.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('accounts_payable_extra_id', 'user_id')
    )
    op.create_table('user_accounts_payable_extra',
    sa.Column('accounts_payable_extra_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['accounts_payable_extra_id'], ['accounts_payable_extra.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('accounts_payable_extra_id', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_accounts_payable_extra')
    op.drop_table('admin_accounts_payable_extra')
    op.drop_table('accounts_payable_extra_detail')
    op.drop_table('accounts_payable_extra')
    # ### end Alembic commands ###
