"""remove report_category from transaction_type

Revision ID: f0a8a9592d66
Revises: 8f95916918c0
Create Date: 2026-05-16 10:21:27.332982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0a8a9592d66'
down_revision = '8f95916918c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_type', schema=None) as batch_op:
        batch_op.drop_column('report_category')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_type', schema=None) as batch_op:
        batch_op.add_column(sa.Column('report_category', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
