"""Add cancellation request fields to deposit table

Revision ID: f2121b701c6c
Revises: 571730995d45
Create Date: 2026-05-23 18:39:42.534622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2121b701c6c'
down_revision = '571730995d45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deposit', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cancellation_requested_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cancellation_requested_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('cancellation_request_reason', sa.String(), nullable=True))
        batch_op.create_foreign_key('fk_deposit_cancellation_requested_by', 'user', ['cancellation_requested_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deposit', schema=None) as batch_op:
        batch_op.drop_constraint('fk_deposit_cancellation_requested_by', type_='foreignkey')
        batch_op.drop_column('cancellation_request_reason')
        batch_op.drop_column('cancellation_requested_at')
        batch_op.drop_column('cancellation_requested_by_id')

    # ### end Alembic commands ###
