"""empty message

Revision ID: feb9b1347ce1
Revises: 8963c3ba3772
Create Date: 2025-12-06 18:36:37.153936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'feb9b1347ce1'
down_revision = '8963c3ba3772'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_class',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_class_name', sa.String(length=255), nullable=True),
    sa.Column('priority', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('account_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_type_name', sa.String(length=255), nullable=True),
    sa.Column('account_class_id', sa.Integer(), nullable=False),
    sa.Column('priority', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['account_class_id'], ['account_class.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin_account_class',
    sa.Column('account_class_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_class_id'], ['account_class.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('account_class_id', 'user_id')
    )
    op.create_table('user_account_class',
    sa.Column('account_class_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_class_id'], ['account_class.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('account_class_id', 'user_id')
    )
    op.create_table('admin_account_type',
    sa.Column('account_type_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_type_id'], ['account_type.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('account_type_id', 'user_id')
    )
    op.create_table('user_account_type',
    sa.Column('account_type_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['account_type_id'], ['account_type.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('account_type_id', 'user_id')
    )
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_type_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('AccountType', 'account_type', ['account_type_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_constraint('AccountType', type_='foreignkey')
        batch_op.drop_column('account_type_id')

    op.drop_table('user_account_type')
    op.drop_table('admin_account_type')
    op.drop_table('user_account_class')
    op.drop_table('admin_account_class')
    op.drop_table('account_type')
    op.drop_table('account_class')
    # ### end Alembic commands ###
